services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5434:5432" # I changed this to 5434 on the host machine side because 5432 was already being used by another container
    restart: unless-stopped

volumes:
  postgres_data:
